name: Build Android APK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    environment: Firebase
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Decode Google Services JSON
        env:
          GOOGLE_SERVICES_BASE64: ${{ secrets.GOOGLE_SERVICES_BASE64 }}
        run: |
          echo $GOOGLE_SERVICES_BASE64 | base64 --decode > app/google-services.json

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install dependencies
        run: npm ci

      - name: Generate git-info.json
        env:
          HEAD_REF: ${{ github.head_ref }}
          REF_NAME: ${{ github.ref_name }}
        run: |
          if [ -n "$HEAD_REF" ]; then
            BRANCH="$HEAD_REF"
          else
            BRANCH="$REF_NAME"
          fi
          echo "{\"branch\": \"$BRANCH\", \"commit\": \"${GITHUB_SHA}\"}" > git-info.json

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: npm
          token: ${{ secrets.EXPO_TOKEN }}
      
      - name: Prebuild
        run: npx expo prebuild --platform android

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant Execute Permission to Gradlew
        run: chmod +x android/gradlew

      - name: Update gradle.properties
        run: echo "org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g" >> android/gradle.properties

      - name: Build APK with Gradle
        working-directory: ./android
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk

  notify:
    if: cancelled() == false
    needs: build
    runs-on: ubuntu-latest
    environment: Notify
    steps:
      - uses: up9cloud/action-notify@master
        env:
          GITHUB_JOB_STATUS: ${{ needs.build.result }}
          TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
          TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
          CUSTOM_VAR1: ${{github.repository_owner}}
